### ISSUE TITLE
AV1 essentials

### ISSUE THREAD

**Issue by lucaderosso** [lucaderosso/AV1#8]
- [x] 1. finish up sounds
- [x] 1.1 include decay controls for all sounds
- [x] 1.2 duplicate 16 pads to have a total of 32 resulting in 4 possible combinations played by performable
- [x] 3. create soundscapes clips to gate via pads
- [x] 4. consider including compression for scapes
- [x] 5. find solution to make some of the drum rack sounds gate scapes clips
- [ ] ~~6. make sequence 64 steps long~~
- [x] 7. consider using fillers (purple pads) to invert color or to even add color)
- [x]  7.1 use fillers to invert color
- [x] 8. consider using incoming audio to brighten the grid
- [x] 9. #6 Layer 1 grids should always between 1 and 4 elements
- [x] 10. #7 On sounds
- [ ] 11. #4 Attack
- [x] 12. #3 Link updateLifeDecay to sound and shapes behavior 
- [ ] 13. #2 Note breath 
- [x] 14. #1 Link sustain and lifeDecay 
- [ ] 15. #5 Bounds seem not being calculated properly
- [x] 16. check aspect ratio issue and make sure full screen fills the width
- [x] 17. check frame rate to make sure it's a multiple of the projector's 

Things I need control for
- [x] new scene
- [x] launch scape clips

**Comment by lucaderosso** [comment]
I consider this done for now.
